name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install loguru pytest
    
    - name: Run tests
      run: |
        pytest stepik/pavel_khoshev/01_course_multithreading_python/test

    - name: Run khoshev_c1_m1_l3_s6
      run: |
        python stepik/pavel_khoshev/01_course_multithreading_python/module/module_01/lesson_03/step_06.py

    - name: Run khoshev_c1_m1_l3_s7
      run: |
        python stepik/pavel_khoshev/01_course_multithreading_python/module/module_01/lesson_03/step_07.py
    
    - name: Run khoshev_c1_m1_l3_s8
      run: |
        python stepik/pavel_khoshev/01_course_multithreading_python/module/module_01/lesson_03/step_08.py
    
    - name: Run khoshev_c1_m1_l3_s9
      run: |
        python stepik/pavel_khoshev/01_course_multithreading_python/module/module_01/lesson_03/step_09.py